[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # status-line
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''

# ==============================================================================
# denite
# ==============================================================================

# ==============================================================================
# edit
# ==============================================================================

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

# ==============================================================================
# colorscheme
# ==============================================================================

[[plugins]] # colorscheme
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'jacoborus/tender'

# ==============================================================================
# languages
# ==============================================================================

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
depends = 'deoplete.nvim'
on_ft = ['rust', 'vue']
build = './install.sh'
rev = 'next'
hook_source = '''
set hidden
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'vue': ['vls'],
    \ }
let g:LanguageClient_autoStart = 1
noremap <silent> H :call LanguageClient_textDocument_hover()<CR>
noremap <silent> Z :call LanguageClient_textDocument_definition()<CR>
noremap <silent> R :call LanguageClient_textDocument_rename()<CR>
noremap <silent> S :call LanugageClient_textDocument_documentSymbol()<CR>
'''

[[plugins]] # Toml
repo = 'cespare/vim-toml'

