dist: trusty
sudo: false

notifications:
  email: false

language: node_js

node_js:
  - 8.9 # Lock to the version shipped with VSCode 1.26+

env:
  matrix:
    - CI_MATRIX_BUILD=true
    - CI_MATRIX_LINT=true

script:
  - |
    if [ "$CI_MATRIX_BUILD" = "true" ]; then
      npm run compile
    elif [ "$CI_MATRIX_LINT" = "true" ]; then
      npm run lint
    else
      echo "This code path is run unexpectedly" 1>&2
      exit 1
    fi